name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Lint/Typecheck/Tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Ruff
        run: ruff check .
      - name: Black
        run: black --check .
      - name: Mypy
        run: mypy app
      - name: Pytest
        run: pytest -q

  docker:
    name: Build & Smoke Test (Docker)
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build multi-arch image
        run: |
          docker buildx build                 --platform linux/amd64,linux/arm64                 -t python-api:ci                 --load                 .
      - name: Run container
        run: |
          docker run -d --name api -p 8000:8000 python-api:ci
          echo "Waiting for health..."
          for i in {1..20}; do
            curl -fsS http://127.0.0.1:8000/api/v1/healthz && break || sleep 1
          done
          curl -fsS http://127.0.0.1:8000/api/v1/version
      # Optional: publish to GHCR on main with a version tag
      # - name: Login to GHCR
      #   if: github.ref == 'refs/heads/main'
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Push image
      #   if: github.ref == 'refs/heads/main'
      #   run: |
      #     IMAGE=ghcr.io/${{ github.repository_owner }}/python-api:latest
      #     docker tag python-api:ci $IMAGE
      #     docker push $IMAGE
